export default (category, city, scores) => {
    const cardDiv = document.createElement("div");
    cardDiv.classList.add("card");
    const contentDiv = document.createElement("div");
    contentDiv.classList.add("content");
    const backDiv = document.createElement("div");
    backDiv.classList.add("back");
    const backContentDiv = document.createElement("div");
    backContentDiv.classList.add("back-content");
    const strongElem = document.createElement("strong");
    strongElem.textContent = category;
    const frontDiv = document.createElement("div");
    frontDiv.classList.add("front");
    const imgDiv = document.createElement("div");
    imgDiv.classList.add("img");
    const circle = document.createElement("div");
    circle.classList.add("circle");
    const circleRight = document.createElement("div");
    circleRight.classList.add("circle");
    circleRight.id = "right";
    const circleBottom = document.createElement("div");
    circleBottom.classList.add("circle");
    circleBottom.id = "bottom";
    const frontContentDiv = document.createElement("div");
    frontContentDiv.classList.add("front-content");
    const badge = document.createElement("small");
    badge.classList.add("badge");
    badge.textContent = city;
    const descriptionDiv = document.createElement("div");
    descriptionDiv.classList.add("description");
    const titleDiv = document.createElement("div");
    titleDiv.classList.add("title");
    const titleParagraph = document.createElement("p");
    titleParagraph.classList.add("title");
    const strongParagraph = document.createElement("strong");
    strongParagraph.textContent = scores;
    const footer = document.createElement("p");
    footer.classList.add("card-footer");
    
    backContentDiv.appendChild(strongElem);
    backDiv.appendChild(backContentDiv);
    imgDiv.appendChild(circle);
    imgDiv.appendChild(circleRight);
    imgDiv.appendChild(circleBottom);
    frontDiv.appendChild(imgDiv);
    frontContentDiv.appendChild(badge);
    titleParagraph.appendChild(strongParagraph);
    titleDiv.appendChild(titleParagraph);
    descriptionDiv.appendChild(titleDiv);
    descriptionDiv.appendChild(footer);
    frontContentDiv.appendChild(descriptionDiv);
    frontDiv.appendChild(frontContentDiv);
    contentDiv.appendChild(backDiv);
    contentDiv.appendChild(frontDiv);
    cardDiv.appendChild(contentDiv);
    return cardDiv;
};