import container from './components/container';
import title from './components/title';
import '../asset/css/style.css';
import searchArea from './components/searchArea';

const titleH1 = title();
const mainContainer = container("mainBox");
const containerBig = document.createElement("div");
const containerCard = document.createElement("div");
containerCard.id = "card-container";
containerCard.classList.add("card-container");
containerBig.classList.add("search-container");
const searchResult = document.createElement("div");
searchResult.id = "search-result";
searchResult.classList.add("resultBox");
const listSearchSuggest = document.createElement("ul");
listSearchSuggest.id = "list-search";
const search = searchArea();
containerBig.appendChild(search);
searchResult.appendChild(listSearchSuggest);
containerBig.appendChild(searchResult);
containerBig.appendChild(containerCard);
mainContainer.appendChild(titleH1);
mainContainer.appendChild(containerBig);
document.body.appendChild(mainContainer);