import container from './component/container';
import path from './component/path';
import title from './component/title';
import '../asset/css/style.css';
import searchArea from './component/searchArea';

const titleH1 = title();
// const input = searchText("input");
// const inputContainer = container("InputContainer");
const mainContainer = container("mainBox");
const containerBig = document.createElement("div");
containerBig.classList.add("test-container");
const searchResult = document.createElement("div");
searchResult.id = "search-result";
searchResult.classList.add("resultBox");
const listSearchSuggest = document.createElement("ul");
listSearchSuggest.id = "list-search";
const search = searchArea();
// inputContainer.appendChild(input);
// inputContainer.appendChild(btn);
// inputContainer.appendChild(searchIcon);
containerBig.appendChild(search);
searchResult.appendChild(listSearchSuggest);
containerBig.appendChild(searchResult);
mainContainer.appendChild(titleH1);
mainContainer.appendChild(containerBig);
document.body.appendChild(mainContainer);